[fr]
  title = "Free Society"
  languageName = "french"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/fr"
  
[en]
  title = "Zzossig's Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
