[fr]
  title = "Fluchère Informatique"
  languageName = "french"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/fr"
  
[en]
  title = "Fluchère Informatique"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
